[package]
name = "agent"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rustls = "0.23.19"
rustls-pemfile = "2.2.0"
thiserror = "2.0.3"
